from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('logout/', views.logout_view, name='logout'),
    path('equipos/', views.equipos_lista, name='equipos_lista'),
    path('equipos/guardar/', views.equipo_guardar, name='equipo_guardar'),
    path('equipos/datos/<str:id_equipo>/', views.equipo_datos, name='equipo_datos'),
    path('equipos/actualizar/<str:id_equipo>/', views.equipo_actualizar, name='equipo_actualizar'),
    path('equipos/nuevo/', views.equipo_form, name='equipo_nuevo'),
    path('equipos/editar/<str:id_equipo>/', views.equipo_form, name='equipo_editar'),
    path('usuarios/', views.usuarios_lista, name='usuarios_lista'),
    path('usuarios/guardar/', views.usuario_guardar, name='usuario_guardar'),
    path('usuarios/datos/<str:id_usuario>/', views.usuario_datos, name='usuario_datos'),
    path('usuarios/actualizar/<str:id_usuario>/', views.usuario_actualizar, name='usuario_actualizar'),
    path('tickets/', views.tickets_lista, name='tickets_lista'),
    path('tickets/actualizacion/', views.tickets_actualizacion, name='tickets_actualizacion'),
    path('tickets/guardar/', views.ticket_guardar, name='ticket_guardar'),
    path('tickets/datos/<str:id_ticket>/', views.ticket_datos, name='ticket_datos'),
    path('tickets/foto/<str:id_ticket>/<int:n>/', views.ticket_foto, name='ticket_foto'),
    path('tickets/actualizar/<str:id_ticket>/', views.ticket_actualizar, name='ticket_actualizar'),
    path('tickets/cerrar/<str:id_ticket>/', views.ticket_cerrar, name='ticket_cerrar'),
    path('tickets/seguimiento/', views.tickets_seguimiento, name='tickets_seguimiento'),
    path('tickets/seguimiento/actualizacion/', views.tickets_seguimiento_actualizacion, name='tickets_seguimiento_actualizacion'),
    path('tickets/atender/<str:id_ticket>/', views.ticket_atender, name='ticket_atender'),
    path('tickets/atencion/datos/<str:id_ticket>/', views.atencion_datos, name='atencion_datos'),
    path('tickets/atencion/imagen/<str:id_ticket>/<int:n>/', views.atencion_imagen, name='atencion_imagen'),
    path('tickets/atencion/guardar/<str:id_ticket>/', views.atencion_guardar, name='atencion_guardar'),
    path('tickets/firma-usuario/guardar/<str:id_ticket>/', views.firma_usuario_guardar, name='firma_usuario_guardar'),
    path('tickets/reporte/<str:id_ticket>/', views.reporte_mantenimiento, name='reporte_mantenimiento'),
    path('tickets/reporte/<str:id_ticket>/pdf/', views.reporte_mantenimiento_pdf, name='reporte_mantenimiento_pdf'),
    path('reservaciones/guardar/', views.reservacion_guardar, name='reservacion_guardar'),
    path('reservaciones/responder/<str:id_reservacion>/', views.reservacion_responder, name='reservacion_responder'),
    path('reservaciones/<str:recurso>/', views.reservaciones_vista, name='reservaciones'),
    path('reservaciones/<str:recurso>/datos/', views.reservaciones_datos, name='reservaciones_datos'),
    path('notificaciones/lista/', views.notificaciones_lista, name='notificaciones_lista'),
    path('notificaciones/leida/<str:id_notificacion>/', views.notificaciones_marcar_leida, name='notificaciones_marcar_leida'),
    path('notificaciones/leidas-todas/', views.notificaciones_marcar_todas, name='notificaciones_marcar_todas'),
    path('configuracion/', views.configuracion_vista, name='configuracion'),
    path('configuracion/niveles/guardar/', views.nivel_guardar, name='nivel_guardar'),
    path('configuracion/niveles/actualizar/<str:id_nivel>/', views.nivel_actualizar, name='nivel_actualizar'),
    path('configuracion/permisos/guardar/', views.permiso_guardar, name='permiso_guardar'),
    path('configuracion/permisos/actualizar/<str:id_permiso>/', views.permiso_actualizar, name='permiso_actualizar'),
    path('configuracion/roles/guardar/', views.rol_guardar, name='rol_guardar'),
    path('configuracion/roles/actualizar/<str:id_rol>/', views.rol_actualizar, name='rol_actualizar'),
]
